//
//  localizationTitles.swift
//  etajerIOS
//
//  Created by mohamed on 7/7/19.
//  Copyright © 2019 Maxsys. All rights reserved.
//

import Foundation

//MARK:- SignIn
let SIGNIN = "SIGNIN"
let CHANGE_LANG = "CHANGE_LANG"
let DONT_HAVE_ACCOUNT = "DONT_HAVE_ACCOUNT"
let SIGNUP_NOW = "SIGNUP_NOW"
let PRIVACY_TEXT = "PRIVACY_TEXT"
let PRIVACY_POLICY = "PRIVACY_POLICY"
let T_C = "T&C"
let AND = "AND"
let SIGNIN_NOW = "SIGNIN_NOW"
let HAVE_AN_ACCOUNT = "HAVE_AN_ACCOUNT"
let EMAIL = "EMAIL";
let PASSWORD = "PASSWORD";

//MARK:- Signup
let SIGNUP = "SIGNUP"
let MOBILE_NUMBER = "MOBILE_NUMBER"
let FIRST_NAME = "FIRST_NAME"
let FAMILY_NAME = "FAMILY_NAME"
let CONFIRM_PASSWORD = "CONFIRM_PASSWORD"
let SIGN_UP = "SIGN_UP"


let ARE_Y_FORGET_PASS =  "ARE_Y_FORGET_PASS"
let ARE_Y_FORGET_PASS_Txt = "ARE_Y_FORGET_PASS_Txt"
let ENTER_YOUR_EMAIL = "ENTER_YOUR_EMAIL"

//MARK:- Home
let CATEGORY_TITLE_1 = "CATEGORY_TITLE_1"
let CATEGORY_TITLE_2 = "CATEGORY_TITLE_2"
let MORE_ITEMS = "MORE_ITEMS"

//MARK:- Item Details

let S_R = "S.R"
