//
//  localizationTitles.swift
//  etajerIOS
//
//  Created by mohamed on 7/7/19.
//  Copyright © 2019 Maxsys. All rights reserved.
//

import Foundation

let OK = "OK"
let CANCEL = "CANCEL"

//MARK:- SignIn
let SIGNIN = "SIGNIN"
let CHANGE_LANG = "CHANGE_LANG"
let DONT_HAVE_ACCOUNT = "DONT_HAVE_ACCOUNT"
let SIGNUP_NOW = "SIGNUP_NOW"
let PRIVACY_TEXT = "PRIVACY_TEXT"
let PRIVACY_POLICY = "PRIVACY_POLICY"
let T_C = "T&C"
let AND = "AND"
let SIGNIN_NOW = "SIGNIN_NOW"
let HAVE_AN_ACCOUNT = "HAVE_AN_ACCOUNT"
let EMAIL = "EMAIL";
let PASSWORD = "PASSWORD";

//MARK:- Signup
let SIGNUP = "SIGNUP"
let MOBILE_NUMBER = "MOBILE_NUMBER"
let FIRST_NAME = "FIRST_NAME"
let FAMILY_NAME = "FAMILY_NAME"
let CONFIRM_PASSWORD = "CONFIRM_PASSWORD"
let SIGN_UP = "SIGN_UP"


let ARE_Y_FORGET_PASS =  "ARE_Y_FORGET_PASS"
let ARE_Y_FORGET_PASS_Txt = "ARE_Y_FORGET_PASS_Txt"
let ENTER_YOUR_EMAIL = "ENTER_YOUR_EMAIL"

//MARK:- Home
let CATEGORY_TITLE_1 = "CATEGORY_TITLE_1"
let CATEGORY_TITLE_2 = "CATEGORY_TITLE_2"
let MORE_ITEMS = "MORE_ITEMS"
let NOT_SIGNIN = "NOT_SIGNIN"

//MARK:- Filter

let FILTAR = "FILTER";
let RESET = "RESET";
let PRODUCT_FILTERATION = "PRODUCT_FILTERATION";
let PRODUCT_TYBE = "PRODUCT_TYBE";
let PRODUCT_CONDITION = "PRODUCT_CONDITION";
let NEW = "NEW";
let USED = "USED";

//MARK:- Item Details

let S_R = "S.R"
let LAST_OVERBID = "LAST_OVERBID"
let ITEM_ADD_TO_CART = "ITEM_ADD_TO_CART"

//MARK:- Auction Details

let BUY_NOW_WITH_PRICE = "BUY_NOW_WITH_PRICE"

let MY_ORDERS = "MY_ORDERS"
let ADDRESSES = "ADDRESSES"
let PAYMENT_INFO = "PAYMENT_INFO"
let MY_INFO = "MY_INFO"

//MARK:- FAVORITES

let FAVORITES = "FAVORITES"
let PRODUCTS = "PRODUCTS"
let SHOPS = "SHOPS"

//MARK:- Notifications

//MARK:- Cart

let CONTINUE = "CONTINUE"
let CONFIRM_THE_OREDER = "CONFIRM_THE_OREDER"

let CONTENUE = "CONTENUE"
let BUY_NOW = "BUY_NOW"

let ENTER_CODE = "ENTER_CODE"
let SUBMIT = "SUBMIT"
let PAYMENT_METHOD = "PAYMENT_METHOD"
let ORDER_SUMMERY = "ORDER_SUMMERY"
let TRANSPORT_TO = "TRANSPOST_TO"
let YOUT_OREDER_ITEMS = "YOUR_ORDER_ITEMS"
let TRANSPORT = "TRANSPORT"
let ORDER_NUMBER = "ORDER_NUMBER"

//MARK:- Addresses

let ALL_FIELDS_ERROR = "ALL_FIELDS_ERROR"
let SELECT_FORM_MAP = "SELECT_FORM_MAP"
let ADDRESS_ADDED = "ADDRESS_ADDED"

//MARK:- My Info

let PASSWORD_CHANED = "PASSWORD_CHANED"
let PASSWORD_NOT_MATCHED = "PASSWORD_NOT_MATCHED"

let LOGOUT = "LOGOUT"
let DO_YOU_WANT_TO_LOGOUT = "DO_YOU_WANT_TO_LOGOUT";
